### ISSUE TITLE
doesn't work with CF7 5.4, action priority changed

### ISSUE THREAD

**Issue by pierstitus** [mnelson4/cf7-only-show-recaptcha-v3-when-needed#1]
The action priority changed from 10 to 20, so needs to be adjusted in the remove_action line to be compatible with CF7 5.4.

    remove_action( 'wp_enqueue_scripts', 'wpcf7_recaptcha_enqueue_scripts', 20, 0 );

Thanks for this plugin!

**Comment by mnelson4** [comment]
oh right on, thanks! I've just made a commit that adds support for CF7 5.4. I actually kept the line using priority 10 too, so that it will keep working for folks on CF7 5.3 and earlier.

Thanks you!

**Comment by mnelson4** [comment]
See https://github.com/mnelson4/cf7-only-show-recaptcha-v3-when-needed/commit/aea2443011da29ecb485ccb71938d25afec27526
